repos:
  - repo: https://github.com/AndreiCostinescu/DevTools
    rev: b8dc86cf13325c0fad39ca464876b91c78779b6e
    hooks:
      - id: license-header-check
        stages: [pre-commit]
      - id: clang-format
        stages: [pre-commit]
      - id: clang-tidy
        stages: [pre-commit]
      - id: dco-check
        stages: [commit-msg]
