repos:
  - repo: https://github.com/AndreiCostinescu/DevTools
    rev: 29aefb602ff4eb8e8df3ad541fc64b441c2a07a1
    hooks:
      - id: license-header-check-cpp
        stages: [pre-commit]
      - id: clang-format
        stages: [pre-commit]
      - id: clang-tidy
        stages: [pre-commit]
      - id: dco-check
        stages: [commit-msg]
