repos:
  - repo: https://github.com/AndreiCostinescu/DevTools
    rev: fba66d8a1f88705d5f3d7ba5c3fef36cc99d4288
    hooks:
      - id: license-header-check
        stages: [pre-commit]
      - id: clang-format
        stages: [pre-commit]
      - id: clang-tidy
        stages: [pre-commit]
      - id: dco-check
        stages: [commit-msg]
